# .vulture_whitelist.py
async_setup_entry  # unused function
async_unload_entry  # unused function
async_press  # unused function
WebastoConfigFlow  # unused class
VERSION  # unused variable
async_step_user  # unused method
async_step_zeroconf  # unused method
async_get_options_flow  # unused method
async_step_init  # unused method
INTEGRATION_VERSION  # unused variable
entity  # unused variable
PHASE_COUNT_MAP  # unused variable
_async_update_data  # unused method
async_get_triggers  # unused function
async_attach_trigger  # unused function
async_get_config_entry_diagnostics  # unused function
_attr_name  # unused attribute
_attr_unique_id  # unused attribute
_attr_icon  # unused attribute
_attr_entity_category  # unused attribute
_attr_device_info  # unused attribute
_attr_native_step  # unused attribute
_attr_native_unit_of_measurement  # unused attribute
_attr_assumed_state  # unused attribute
_attr_native_value  # unused attribute
_variant_max_current  # unused attribute
_attr_device_class  # unused attribute
_attr_state_class  # unused attribute
_attr_options  # unused attribute
_attr_translation_key  # unused attribute
