name: Bug report
description: Report an issue with the Webasto Next Modbus integration
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve the integration! Please fill out the details below so issues can be triaged quickly.
  - type: dropdown
    id: install_method
    attributes:
      label: Installation method
      description: How was the integration installed?
      options:
        - HACS (stable release)
        - HACS (beta release)
        - Manual copy
        - Other
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Integration version
      description: Version number shown in the manifest or HACS entry (for example, 0.2.0).
      placeholder: 0.2.0
    validations:
      required: true
  - type: input
    id: ha_version
    attributes:
      label: Home Assistant version
      description: Please include the full Home Assistant version (Settings → About).
      placeholder: 2024.12.0
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Problem description
      description: What happened and what did you expect to happen?
      placeholder: Describe the observed behaviour...
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: List the steps that reproduce the issue.
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant logs
      description: Paste any relevant log entries (enable debug logging if helpful).
      render: shell
  - type: input
    id: modbus_setup
    attributes:
      label: Wallbox model / Modbus setup
      description: Include information about the wallbox variant, firmware, and connection specifics.
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to avoid duplicates.
          required: true
        - label: I am willing to help debug further and provide additional logs if needed.
